# Generated by Django 2.2.5 on 2019-10-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20190921_2313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'course', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('last_name', 'first_name', 'nick_name')},
        ),
    ]
